Add function to port forward to local stream to support VSCode remote ssh target.
mkj/dropbear pull request #199
Opened 2022-12-05 19:10 UTC by puppywang

VSCode remote ssh plugin need to create port forward between local port and remote unix socket, which is not yet support by current version of dropbear, this patch add a simple impl of port forwarding to local stream, only test on centos, debian x64, should world on any other linux variant. Any advice is welcome, thanks.

2022-12-22 05:05 UTC, mkj requested changes
Thanks, this seems useful. I've added a few comments inline for changes.

One other thing that needs changing is `connect_try_next()`. It should skip the `fastopen` path when it's `AF_UNIX` family, and according to the `connect(2)` manpage it should be testing `EAGAIN` rather than `EINPROGRESS` for unix sockets. If you'd prefer I can make those changes later.

I guess "tcpfwd" isn't an accurate file name any more - maybe the files should be renamed to svr-fwd.c, cli-fwd.c, fwd.h. Again, I'm happy to change that separately.

2022-12-22 05:05 UTC, mkj commented on netio.c
> +	if (strlen(localpath) > sizeof(sunaddr->sun_path)) {
This should be `>=` not `>`, need space for the null terminator

2022-12-22 06:18 UTC, puppywang commented
Thanks for your reply, I will fix those issues later.

2022-12-23 08:33 UTC, puppywang commented
All issues resolved.

2024-04-03 14:47 UTC, merged

2024-04-03 14:47 UTC, mkj commented
Thanks, sorry for the delay getting this merged