added selinu support
mkj/dropbear pull request #70
Opened 2018-11-11 12:02 UTC by ensc

Commit adds SELinux support to dropbear by:

- adding a new '--enable-selinux' option to configure; by default, it
  is disabled.  This option defines an ENABLE_SELINUX preprocessor
  macro.

- mapping the unix username to the SELinux user which is stored in a
  new 'user_sid' attribute in the AuthState object

- relabeling the controlling pty

- setting the context for the next execve() call to the user_sid

Operations above will not be done when SELinux is disabled.  Failures will
generate LOG_ERR messages and in enforcing SELinux mode, dropbear_exit()
will be called.

Signed-off-by: Enrico Scholz <enrico.scholz@ensc.de>

2018-11-12 15:01 UTC, mkj requested changes
Thanks. I've noted a few changes.
Out of interest what platform are you using?

2018-11-23 14:44 UTC, ensc commented on Makefile.in
> +CFLAGS+=-DENABLE_SELINUX
ok; I replaced this with some more autoconf/autoheader integration:

- the `DROPBEAR_ENABLE_SELINUX` macro is now defined  automatically in `config.h`
- there was added a `LIBSELINUX_LIBS` makefile variable (which can be overridden at `./configure` time) which is applied to server build only

2018-11-23 14:45 UTC, ensc commented on auth.h
> +#ifdef ENABLE_SELINUX
I use now everywhere

```
#ifdef DROPBEAR_ENABLE_SELINUX
```

2018-11-23 14:47 UTC, ensc commented on common-session.c
> +	initselinux(ses.authstate.pw_name);
ok; I redesigned this so that SELinux related code is executed only in `svr-*.c`.

2018-11-23 14:58 UTC, ensc commented on svr-chansession.c
> +	class = string_to_security_class("chr_file");
I added a check

2018-11-23 15:05 UTC, ensc commented
I think, I addressed all the issues.

I am using it in an OpenEmbedded based project:

- see https://gitlab.com/ensc-groups/bpi-router for toplevel project
- the SELinux related changes are in https://gitlab.com/ensc-groups/bpi-router/de.ensc.bpi-router/tree/master/meta-core/recipes-selinux/dropbear
- the dropbear SELinux policy (based upon recent 'minimum' policy) is in https://gitlab.com/ensc-groups/bpi-router/tools/selinux-policy/tree/master/policy; perhaps labeling `dropbear` files as `sshd_exec_t` will work too but I never tried it
- you will need something like https://gitlab.com/ensc-groups/bpi-router/tools/selinux-policy/blob/master/contexts/default_contexts

2026-06-17 07:43 UTC, closed without merging